<?php if ($action == "block.get.option" ) { ?>
    <?php $block = $print_data["data"]["block"]; ?>
    <?php if (isset($block)) { ?>
        <form>
            <?php $controller->get_SettingGrid($block->getId(),$block->getNamePack(), $block->getNameTemplate());?>
            <div class="make-up-box-control">
                <button class="btn-design btn-submit" type="submit">Сохранить</button>
            </div>
        </form>
    <?php } else { ?>
        оШИБКА НЕ НАЙДЕНО НАСТРОЕК ТА КАК БЛОК НЕ СУЩЕСТВУЕТ
    <?php }?>
<?php } else if ($action == "blocks.get" ) { ?>
    <?php $return_data = $print_data["data"]; ?>
    <?php echo json_encode($return_data); ?>
<?php } else if ($action == "block.get.style" ) { ?>
    <?php echo $print_data["data"]["style"]; ?>
<?php } else if ($action == "block.get.code" ) { ?>
    <?php echo $print_data["data"]["code"]; ?>
<?php } else if ($action == "block.add" ) { ?>
    <div class="makeup-add"><div class="makeup-add-button_area"><button class="makeup-add-button btn-design" insert-position="0"><i class="fa fa-plus fa-lg" aria-hidden="true"></button></i></div></div>
    <?php $insert_position = 1; ?>
    <?php foreach ( $print_data["data"] as $key => $block ) { ?>
        <div class="makeup-block clear-fix" id="<?php echo $block->getId() ?>">
            <div class="makeup-view" id="<?php echo $controller->_getSuffix(); ?><?php echo $key; ?>">
                <?php echo $controller->_getContent($block->getNamePack(),$block->getNameTemplate(),$block->getConfig(),$block->getId()); ?>
            </div>
            <div class="makeup-view-option">
                <button class="makeup-edit btn-design" name-pack="<?php echo $block->getNamePack(); ?>" id-section="<?php echo $key; ?>" name-template="<?php echo $block->getNameTemplate(); ?>"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i></button>
                <button class="makeup-remove btn-design" id-section="<?php echo $key; ?>"><i class="fa fa-trash fa-lg" aria-hidden="true"></i></button>
            </div>
        </div>

        <div class="makeup-add"><div class="makeup-add-button_area"><button class="makeup-add-button btn-design" insert-position="<?php echo $insert_position;?>"><i class="fa fa-plus fa-lg" aria-hidden="true"></button></i></div></div>
        <?php $insert_position++;?>
    <?php } ?>
<?php } else if ($action == "block.remove" ) { ?>
    <div class="makeup-add"><div class="makeup-add-button_area"><button class="makeup-add-button btn-design" insert-position="0"><i class="fa fa-plus fa-lg" aria-hidden="true"></button></i></div></div>
    <?php $insert_position = 1; ?>
    <?php foreach ( $print_data["data"] as $key => $block ) { ?>
        <div class="makeup-block clear-fix" id="<?php echo $block->getId() ?>">
            <div class="makeup-view" id="<?php echo $controller->_getSuffix(); ?><?php echo $key; ?>">
                <?php echo $controller->_getContent($block->getNamePack(),$block->getNameTemplate(),$block->getConfig(),$block->getId()); ?>
            </div>
            <div class="makeup-view-option">
                <button class="makeup-edit btn-design" name-pack="<?php echo $block->getNamePack(); ?>" id-section="<?php echo $key; ?>" name-template="<?php echo $block->getNameTemplate(); ?>"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i></button>
                <button class="makeup-remove btn-design" id-section="<?php echo $key; ?>"><i class="fa fa-trash fa-lg" aria-hidden="true"></i></button>
            </div>
        </div>

        <div class="makeup-add"><div class="makeup-add-button_area"><button class="makeup-add-button btn-design" insert-position="<?php echo $insert_position;?>"><i class="fa fa-plus fa-lg" aria-hidden="true"></button></i></div></div>
        <?php $insert_position++;?>
    <?php } ?>
<?php } else if ($action == "block.set" ) { ?>

<?php } ?>