<header class="makeup-header">
    <nav class="makeup-navigation clear-fix">
        <a class="makeup-button-back">
            <i class="fa fa-angle-left" aria-hidden="true"></i>
            <span class="title">Back</span>
        </a>
        <div class="control">
            <button class="btn-design"><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
        </div>
    </nav>
</header>
<section class="makeup-designer clear-fix">
    <div class="makeup-add"><div class="makeup-add-button_area"><button class="makeup-add-button btn-design" insert-position="0"><i class="fa fa-plus fa-lg" aria-hidden="true"></button></i></div></div>
    <?php $insert_position = 1; ?>
    <?php foreach ( $blocks as $key => $block ) { ?>
        <div class="makeup-block clear-fix" id="<?php echo $key; ?>">
            <div class="makeup-view" id="<?php echo $suffix; ?><?php echo $key; ?>">
                <?php echo $controller->_getContent($block->getNamePack(),$block->getNameTemplate(),$block->getConfig(),$key); ?>
            </div>
            <div class="makeup-view-option">
                <button class="makeup-edit btn-design" name-pack="<?php echo $block->getNamePack(); ?>" id-section="<?php echo $key; ?>" name-template="<?php echo $block->getNameTemplate(); ?>"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i></button>
                <?php //<button class="makeup-option btn-design"><i class="fa fa-cog fa-lg" aria-hidden="true"></i></button> ?>
                <button class="makeup-remove btn-design" id-section="<?php echo $key; ?>"><i class="fa fa-trash fa-lg" aria-hidden="true"></i></button>
                <?php //<button class="makeup-change-position btn-design"><i class="fa fa-align-justify fa-lg" aria-hidden="true"></i></button> ?>

            </div>
        </div>

        <div class="makeup-add"><div class="makeup-add-button_area"><button class="makeup-add-button btn-design" insert-position="<?php echo $insert_position;?>"><i class="fa fa-plus fa-lg" aria-hidden="true"></button></i></div></div>
        <?php $insert_position++;?>
    <?php } ?>
</section>
<div class="makeup-modal option">
    <div class="makeup-modal-container">
        <div class="makeup-modal-title">
            Удалить?
        </div>
        <div class="makeup-modal-body">

        </div>
    </div>
</div>
<div class="makeup-modal setting">
    <div class="makeup-modal-container">
        <div class="makeup-modal-title">
            Удалить?
        </div>
        <div class="makeup-modal-body">
            <div class="group_control">
                <button>Да</button>
                <button>Нет</button>
            </div>
        </div>
    </div>
</div>
<div class="makeup-modal remove">
    <div class="makeup-modal-container">
        <div class="makeup-modal-title">
            Удалить?
        </div>
        <div class="makeup-modal-body">
            <div class="group_control">
                <button>Да</button>
                <button>Нет</button>
            </div>
        </div>
    </div>
</div>
<div class="makeup-modal pack_browser">
    <div class="makeup-modal-container">
        <div class="makeup-modal-title">
            Браузер выбора пака
        </div>
        <div class="makeup-modal-body">
            <div class="make-up-box-control">
                <div class="make-up-pack-selector"></div>
            </div>
        </div>
    </div>
</div>