<div class="makeup-preloader">
    <ul>
        <li class="gray">
            <span class="top"></span>
            <span class="bottom"></span>
            <div class="pre-left-bar"></div>
            <div class="pre-right-bar"></div>
        </li>
        <li class="red">
            <span class="top"></span>
            <span class="bottom"></span>
            <div class="pre-left-bar"></div>
            <div class="pre-right-bar"></div>
        </li>
        <li class="black">
            <span class="top"></span>
            <span class="bottom"></></span>
            <div class="pre-left-bar"></div>
            <div class="pre-right-bar"></div>
        </li>
        <li class="blue">
            <span class="top"></span>
            <span class="bottom"></span>
            <div class="pre-left-bar"></div>
            <div class="pre-right-bar"></div>
        </li>
    </ul>
</div>