<section class="reviews">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>отзыв</h3>
            </div>
        </div>
        <!-- /row -->
        <div class="row">
            <div class="col-sm-1">
                <div class="thumbnail">
                    <img class="img-responsive user-photo" src="image/user.jpg">
                </div><!-- /thumbnail -->
            </div><!-- /col-sm-1 -->
            <div class="col-sm-5">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>юзер</strong> <span class="text-muted">коммент</span>
                    </div>
                    <div class="panel-body">
                        панель
                    </div><!-- /panel-body -->
                </div><!-- /panel panel-default -->
            </div><!-- /col-sm-5 -->
            <div class="col-sm-1">
                <div class="thumbnail">
                    <img class="img-responsive user-photo" src="image/user.jpg">
                </div><!-- /thumbnail -->
            </div><!-- /col-sm-1 -->
            <div class="col-sm-5">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>юзер</strong>
                        <span class="text-muted">комент</span>
                    </div>
                    <div class="panel-body">
                        панель
                    </div><!-- /panel-body -->
                </div><!-- /panel panel-default -->
            </div><!-- /col-sm-5 -->
        </div><!-- /row -->
    </div><!-- /container -->
</section>