<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">

    <?php echo $this->headTitle('ZF2 ')?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo $this->headLink() ?>

    <?php echo $this->headScript() ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/image/favicon.ico'))
        ->prependStylesheet('css/bootstrap/bootstrap.css')
        ->prependStylesheet('css/font-awesome.css')
        ->prependStylesheet('style.css')
//            ->prependStylesheet($this->basePath('css/autogen/style.css'));

    ; ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile('js/bootstrap.min.js')
        ->prependFile('js/jquery.min.js')
        ->prependFile('js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('js/html5shiv.min.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>
<body>
    <?php echo $save_data; ?>
</body>
</html>
