<style>
    .dialog-picker-<?php echo $setting["option"]; ?> {
        position: fixed;
        z-index: 2043;
        top: 50%;
        left: 50%;
        width: 600px;
        height: 500px;
        margin-left: -300px;
        margin-top: -250px;
        display: none;
    }
    .file-browser-control {
        height: 98%;
        width: 98%;

        margin-top: 1%;
        padding: 10px;

        background-color: #fff;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;

        top: 0;
        left: 50%;
        margin-left: -49%;

        position: absolute;
        overflow-y: scroll;
        z-index: 2023;
    }
    .loadimageControl{

    }
    .imageControl{

    }
</style>
<div class="make-up-box-control">
    <label class="title-box"><?php echo $setting["title"]; ?></label>
    <div class="body-box">
        <input class="hidden-<?php echo $setting["option"]; ?>" type="hidden" value="<?php echo $setting["default"]; ?>" name="<?php echo $setting["option"]; ?>">
        <div class="control-<?php echo $setting["option"]; ?>"><img src='<?php echo $setting["default"]; ?>' width="200" /></div>
        <div class="dialog-picker-<?php echo $setting["option"]; ?>"></div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var start_action = false;

        $(".control-<?php echo $setting["option"]; ?>").unbind("click");
        $(".control-<?php echo $setting["option"]; ?>").click(function () {
            $(".dialog-picker-<?php echo $setting["option"]; ?>").css("display","block");
            $(".dialog-picker-<?php echo $setting["option"]; ?>").FileBrowser(
                {
                    iconSize:"small",
                    selectImageAction : function (data) {
                        $(".control-<?php echo $setting["option"]; ?> img").attr("src",data.url);
                        $(".hidden-<?php echo $setting["option"]; ?>").val(data.url);
                        $(".dialog-picker-<?php echo $setting["option"]; ?>").css("display","none");
                    },
                    selectFileAction : function (data) {
                        alert(data.url);
                    }
                }
            );
        });
    });
</script>
<style>
    .control-<?php echo $setting["option"]; ?>{
        display: block;
        margin: 0 auto;
        text-align: center;
        padding: 4px;
        border-radius: 3px;
        border: 1px solid #a1a1a1;
    }
</style>
