<section class="description">
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-md-offset-3">
				<img src="image/evolution.png" alt="" class="img-responsive">
				<h4 class="h4 text-center">
					Заголовок
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum omnis odio quo, adipisci deserunt deleniti, exercitationem, nesciunt labore, nam sunt repellendus ratione maiores consectetur dolore iure provident sit porro quisquam.
				</p>
				<button class="btn btn-default" type="button">
					Ознакомится
				</button>
			</div>
			<div class="col-md-3">
				<img src="image/evolution.png" alt="" class="img-responsive">
				<h4 class="h4 text-center">
					Заголовок
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta porro laborum ipsa earum sed ad, voluptas necessitatibus vel quis fugiat, sit eos quod magni amet explicabo reiciendis est esse! Repellendus.
				</p>
				<button class="btn btn-default" type="button">
					Ознакомится
				</button>
			</div>
		</div>
	</div>
</section>