<section class="info sec1">
	<div class="container">
		<div class="row">
			<h2 class="text-center h2">
				Заголовок
			</h2>
		</div>
		<div class="row">
			<div class="b-info">
				<div class="col-md-6">
					<h4 class="text-center h4">
						Под заголовок для текста
					</h4>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora totam, eaque, aspernatur non possimus ab dolor. Excepturi libero dolorum quam provident perferendis, voluptatibus expedita dicta consequatur magni. Ducimus incidunt, nam.
					</p>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci asperiores iure consequuntur aut, molestias cum! Eius quasi dignissimos nobis dolores maiores laborum animi labore modi alias fugit veritatis, atque dolor.
					</p>
				</div>
				<div class="col-md-6">
					<div class="b-info__form">
						<form action="">
							<h5 class="h5 text-center">
								Tекст для формы
							</h5>
							<div class="form-group">
								<input type="text" placeholder="Ваше имя">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш телефон">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш email">
							</div>
							<button type="button" class="btn btn-danger">Конопулька для формы</button>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="b-info_bottom-button text-center">
				<button class="btn btn-primary" type="button">
					Нижняя кнопка 
				</button>
			</div>
		</div>
	</div>
</section>