<section class="footers">
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-2 col-sm-6 footerleft text-center">
					<div class="logofooter">ЛОГО</div>
				</div>
				<div class="col-md-4 col-sm-6 paddingtop-bottom">
					<div class="post">
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, perspiciatis? 
						</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 pull-right paddingtop-bottom text-center">
					<div class="post">
						<h6 class="heading7">
							+7(999)999 99 99
						</h6>
						<button type="button" class="btn btn-default">Заказать</button>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 paddingtop-bottom text-center">
					<h6 class="heading7">Заголовок</h6>
					<div class="logofooter">
						ЛОГО
					</div>
				</div>
			</div>
		</div>
	</footer>
</section>