<section class="home">
	 <div class="container">
          <div class="row text-center">
            <h1>
            	Заголовок самый основной 
            </h1>
            <div class="text">
              <p>
                Под заголовок тектса
              </p>
            </div>
          </div>
          <div class="row text-center">
          	<p>
          		Далеко-далеко за словесными горами в стране, гласных и согласных живут рыбные тексты. 
          	</p>
          	<div class="home-b text-center">
          		<button class="btn btn-warning  btn-lg">
          			заказать
          		</button>
          	</div>
          </div>
        </div>
</section>