<section id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class=""></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item">
            <img class="first-slide" src="/module/Admin/src/Admin/Templates/arize/image/gugl_4.jpg" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Огромный заголовок.</h1>
                    <p>Мелкое описание того или чего нибудь иного.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">кнрпка</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img class="second-slide" src="/module/Admin/src/Admin/Templates/arize/image/gugl_4.jpg" alt="Second slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Огромный заголовок</h1>
                    <p>Мелкое описание того или чего нибудь иного.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">кнопка</a></p>
                </div>
            </div>
        </div>
        <div class="item active">
            <img class="third-slide" src="/module/Admin/src/Admin/Templates/arize/image/gugl_4.jpg" alt="Third slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Огромный заголовок.</h1>
                    <p>Мелкое описание того или чего нибудь иного.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">кнопка</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</section>